### ISSUE TITLE
Not compatible with ERC20 smart contracts

### ISSUE THREAD

**Issue by rukolahasser** [ava-labs/avalanchego#1008]
**Describe the bug**
avalanche go client is not compatible with ERC20 token smart contracts from [OpenZeppelin](https://openzeppelin.com/).
It's missing some methods to be implemented.

**To Reproduce**
1. Get [ERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol)
2. Generate `.go` file from the `.sol` above, and pass avalanche client as the parameter like this
```
contract, err := NewIERC20(address, client)
```

**Expected behavior**
Expected to interact with ERC20 programmatically.

**Screenshots**
<img width="586" alt="Screen Shot 2022-02-11 at 00 05 27" src="https://user-images.githubusercontent.com/8075702/153447212-743c8b0f-1183-458d-a067-8fdd93306337.png">

**Operating System**
Mac OS

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by gatesyp** [comment]
Do you need to use ANTs / ARC-20 instead? 
https://docs.avax.network/build/references/coreth-arc20s/

**Comment by rukolahasser** [comment]
@gatesyp Could you give me an example of how to do it programmatically?

**Comment by StephenButtolph** [comment]
What client are you passing in? There are various APIs - each with their own client implementation. If you are attempting to connect to the C-chain you should be using a client from coreth.

**Comment by aaronbuchwald** [comment]
It's not clear what `*avaxclient.Client` is since that is not in AvalancheGo or coreth. Could you link to the backend that you are trying to use and what specifically you are trying to pass it into?

You should be using the coreth ethclient to interact with the C-Chain: https://github.com/ava-labs/coreth/blob/master/ethclient/ethclient.go. However, there are some incompatibilities between this and the client offered by go-ethereum since some of the concepts from Ethereum are not applicable to the C-Chain ie. there is no PendingBlock so the functions concerning a pending block are removed ie. `PendingBlock`, `PendingNonceAt`, etc. If you are using the abi package, you may want to use the abi package in coreth: https://github.com/ava-labs/coreth/tree/master/accounts/abi.

**Comment by rukolahasser** [comment]
Thanks for your reply. I managed to do that somehow.
