### ISSUE TITLE
Feature Request: Add filters, sorting, pagination to P-Chain API platform.getCurrentValidators endpoint

### ISSUE THREAD

**Issue by shibacrypt** [ava-labs/avalanchego#1076]
The motivation of this feature request is to get all validators information from the P-Chain in an efficient way. The current `platform.getCurrentValidators` API returns a massive `6.6 MB` json response which is rather heavy.

I could think that users would like do queries along this line:
1. Validators that has `startTime` after X timestamp
2. Validators that has > X% `uptime`
3. Validators that have `delegation fees` < X%
4. Top/bottom Y validators that has X% `uptime`, paginated with size=Z

The filters can't be exact matches (`uptime=0.99`) as it has to serve filtering with operators like `greaterThan` and `lesserThan` etc.

**Comment by abi87** [comment]
Hello @shibacrypt,
we just released  [Banff 9](https://github.com/ava-labs/avalanchego/releases/tag/v1.9.9) which does change `platform.getCurrentValidators` to limit amount of data returned.
The changes are as follows:
1. If no NodeID is specified, `platform.getCurrentValidators` will return all validators without information for every single delegator. Instead just aggregated delegators count and weight will be returned.
2. If multiple NodeIDs are specified, `platform.getCurrentValidators` returns the requested validators without information for every single delegator. Instead just aggregated delegators count and weight will be returned
3. if a single NodeID is specified, `platform.getCurrentValidators` returns validator and all of its delegators complete information.

These changes solve the massive json returned issue (which grew larger since you opened this issue).
We currently don't have plans to allow more complex queries available directly in avalanchego.
Hope this late answer is still useful.
