### ISSUE TITLE
Is Avalanche synchronizing the latest block?

### ISSUE THREAD

**Issue by liuhongfei0517** [ava-labs/avalanchego#1135]
Hi, I am new to Avalanche, I have a few questions to ask
1. The following is the log information after I upgrade an Avalanche node through a script. It is not sure whether the node is running normally
2. Check whether snapshots can be used to synchronize an Avalanche node.
3. How do I view the latest blocks synchronized to a node
Help to answer the above questions, thank you very much!
![image](https://user-images.githubusercontent.com/105718312/188611819-4065269b-82cd-4d06-a568-c6cb04a5b940.png)

**Comment by abi87** [comment]
Hello @liuhongfei0517. My answer come with quite some delay, but I hope it'll be stil useful.

1. The node is running normally. What logs show is a background indexing happening within proposerVM, which is a special VM implementing Snowman++, our protocol to reduce network congestion. Note that the indexing is carried out in background; we also took care to cap the resources taken while indexing. This is a once-only operation, so you won't see it happening again after it completes successfully.
2. We do have state sync support for the C-chain. Our state sync implementation retrieves from the network peers the latest state summary available and proceed then to rebuild the state associated with it, instead of downloading and executing all C-chain blocks from genesis up to current frontier. Some block bootstrapping may happen once state sync completes since the block frontier may have moved up while node was busy rebuilding state sync state.
3.  You'll be able to query the last accepted block via node API once the node has done bootstrapping. Before that what logs show is how many blocks have been processed. Note that in bootstrapping blocks are downloaded "backwards", from frontier back to genesis and then executed "upwards" from the lowest to highest height.

**Comment by abi87** [comment]
Hello  @liuhongfei0517,
We have just added some documentation explaining the bootstrap process [here](https://docs.avax.network/nodes/maintain/node-bootstrap).
I am going ahead and closing down this issue. You are welcome to open another one, here or in [our docs repo](https://github.com/ava-labs/avalanche-docs/issues) should there be more questions.
