### ISSUE TITLE
P-Chain Remote DoS

### ISSUE THREAD

**Issue by visualbasic6** [ava-labs/avalanchego#1217]
Hi,

Anecdotal, but Ava Labs doesn't pay out on valid bug submissions. They technically have a bug bounty program, but if in scope items are dismissed as out of scope, I see no quicker path to resolving a bug than by posting it publicly.

Fire drill!

Sending the following request at warp speed causes a DoS in P-Chain and appears to render nodes useless.

```
POST /ext/bc/P HTTP/1.1
Host: node-ip:api-port
Content-Type: application/json
Content-Length: 77

{"id":2,"method":"platform.getCurrentValidators","params":{},"jsonrpc":"2.0"}
```

If there are too many results, should they not be paginated? Best practices in caching? What's the move?

![image](https://user-images.githubusercontent.com/38997186/217990989-81d65cc0-b048-4f8b-9171-90898e9eca43.png)

More info: https://twitter.com/123456/status/1623855584469561344

Thanks!

**Comment by collincusce** [comment]
Hey can someone re-label this as a feature request? Should simplify the conversation.

The API takes a while with lots of results. @visualbasic6 would like to see pagination of some kind.

**Comment by visualbasic6** [comment]
It's more of a bug than a feature request. I don't think we should take the sweep it under the rug approach. Ava Labs patched their public API server by returning 30x less response data than it had been previously - and in the process of their rate limiting and caching - they misconfigured it so badly that network functionality started dropping all over the place.

"Nothing to see here" isn't the answer - we need a real fix for this...

Because there are issues...

No need to be dishonest or gaslight the community. Didn't you write these docs? In any case, let's get a proper patch going.

![image](https://user-images.githubusercontent.com/38997186/218329713-35dfe4c4-692a-463a-8fee-18864fcdf548.png)

![image](https://user-images.githubusercontent.com/38997186/218329683-fc46fe74-efe8-489e-a07a-d57d05e0431c.png)

![image_2023-02-11_15-10-10](https://user-images.githubusercontent.com/38997186/218329693-89c88c94-6203-44d3-841a-4e43022cab63.png)

![image](https://user-images.githubusercontent.com/38997186/218329699-4a446693-e768-4900-9b1b-608a23959e14.png)

**Comment by collincusce** [comment]
No man I'm doubling down. It hasn't affected the network and it's been there since launch. It's not an actual bug. Now maybe there's something to be said for RPCs being able to hang nodes? Those processes should probably be split out. That would probably cross between a bug and a future request. But specifically to this RPC it's a feature request to ask for pagination.

**Comment by visualbasic6** [comment]
You are free to double down but in the 4 screenshots I just posted it is clear that there is a bug present.

**Comment by collincusce** [comment]
https://twitter.com/CollinCusce/status/1624842942736113673?t=BgWt2V4Y32qyk0LMccnrSA&s=19

**Comment by visualbasic6** [comment]
Wait..

I'm an "extortionist" for requesting an industry standard bug bounty? I don't want $ from Ava Labs - I want acknowledgement of my work and for it to stop being called fake by bagholders. This is about 1's and 0's not how people *feel* about a blockchain they own coins on.

Personal attacks on GitHub are not helpful.

**Comment by collincusce** [comment]
I'm not a bag holder at the moment (someday again for sure). I'm invested in ego alone 🤣. Look, I used the term "extort" tongue-in-cheek. You DID complain about not getting a bounty and hear tale you were rude in discord..I'm stepping away now.

Nice feature request for that API call. Worth considering an overall pagenation system on all "list" RPCs, in my opinion.

**Comment by StephenButtolph** [comment]
Before responding to this issue, I’d first like to clarify the difference between the Avalanche Network and the API server provided by avalanchego. The API server is [intended](https://github.com/ava-labs/avalanche-docs/blob/71ab5283bd3164570bb6acd3fd961aaa2047b496/scripts/avalanchego-installer.sh#L375-L376) and [documented](https://docs.avax.network/apis/avalanchego/apis/issuing-api-calls) to be a local utility which can provide easy access to the current state of the Avalanche Network and does not make any attempt to limit/meter abusive access patterns. Default installations of avalanchego [do not expose this API server publicly](https://github.com/ava-labs/avalanchego/blob/45ec88151f8a0e3bca1d43fe902fd632c41cd956/config/flags.go#L199). Security of the Avalanche Network is provided by the correct functioning of validator nodes. Since validator API servers must not be accessible, this means that application logic only triggered through the access of the API will not impact validator nodes.

We already [planned on modifying this method](https://twitter.com/_patrickogrady/status/1620934614180327425) to only return delegators when a single NodeID is requested. The updated code for `platform.getCurrentValidators` can be seen [here](https://github.com/ava-labs/avalanchego/commit/3000fd316252acff437bc3b0c4259d0d2e97c271). We have been working on optimizing this method for some time as the number of delegators on the Avalanche Network increased (from a few thousand to 60,000+) and the latency of this method degraded. In v1.9.8, for example, we reduced the latency of the method by 80% by adding additional caching to the node, as mentioned in the [release thread](https://twitter.com/_patrickogrady/status/1620934614180327425).

Additionally, we will take this feedback around the API server as an opportunity to:
- [explicitly warn](https://github.com/ava-labs/avalanchego/commit/ea4525d2365e76013c8a44c56f4f303e6f99edc4) nodes that are binding the API server to a potentially public IP
- [update the wording](https://github.com/ava-labs/avalanche-docs/pull/1208) in the install script

The Avalanche Foundation actively engages with the security community and rewards the responsible disclosure of security issues on the Avalanche Network and in avalanchego. Here are some recent examples of this collaboration:
- https://medium.com/avalancheavax/security-analysis-of-avalanche-consensus-39543d09af4a 
- https://medium.com/avalancheavax/apricot-phase-6-native-asset-call-deprecation-a7b7a77b850a
- https://twitter.com/peter_szilagyi/status/1567835617932808193

**Comment by Hellobloc** [comment]
The definition of a vulnerability is based on its impact and the difficulty of exploitation. For this so-called DOS vulnerability, it's actually a DDOS attack where all RPC services go down in a huge amount of attack, and the impact is that it won't even have any effect on the blockchain network, you want to attack all servers, you have to figure out how to connect to all nodes's  RPC ports .

**Comment by abebeos** [comment]
Thing is that attackers have more creativity than hundreds if not thousands of folks like @collincusce , @StephenButtolph and @Hellobloc together.

Highly disappointed how this issue is processed.

## expected

- someone has found a way to bring one(!) node down? Pay out amount n (even if just a small amount compared to the high protocol bounties etc.)
- discussions re the issue  reduce complexity, instead of increasing it



> We already [planned](https://twitter.com/_patrickogrady/status/1620934614180327425)

Ava labs should start planning how to get help with development. Far too slow.

P.s. Stick to issue trackers. What is this twitter-mania?

**Comment by collincusce** [comment]
The Twitter mania was caused by the person who reported it. He decided to take the Twitter when he didn't get his results.

I can bring down every single node on every single L1 network if I have direct RPC access. Guaranteed. It's called DoSing yourself. And that's what this midwit tried to pass as a vulnerability. Be disappointed, I guess. Wallow in it or something.

**Comment by Hellobloc** [comment]
@abebeos 
Well, here's the situation. The originator of this problem himself didn't even fully explain his problem, he performed a Dos attack on an RPC service with an inefficient implementation, this type of Dos attack would not be recognized at all, after all almost all RPC services have this type of problem. 
And he wants to tell everyone that his so-called DOS attack is harmful, but can't explain what the harm is, and doesn't give a complete chain of attacks. He doesn't even figure out if the RPC service is public, or if it is common to filter out some RPC measures with some proxies.

Just like he throws out a DOS and tells everyone his vulnerability is OK and he wants a bounty, isn't that just being a hooligan? If this can be considered a vulnerability, `Geth's` RPC for `unlocking accounts` I think can be exchanged for tens of thousands of dollars.

And then another person(@abebeos ) ran out and told us, that the attackers were smart and they would figure out other ways to do this DOS attack and they would bypass all the challenges we raised. You are so full of crap!


Suggest you learn what a vulnerability is and how to define a vulnerability before you communicate with us, instead of going around shouting about how bad the bounty on algorand and AVAX is.

I'm a big fan of avax, they treat things with a level of seriousness and professionalism that people like you can't match, please read the question first before posting.

To be honest avax is not stingy with the bounty for vulnerabilities, but this question is outrageous. If his problem is rewarded, then all the project's funds will be used to reward such problems that are not problems. To be honest, even those open questions in `issues` are more valuable than this one.

**Comment by Hellobloc** [comment]
![image](https://user-images.githubusercontent.com/113746997/221561291-1e97b2e4-bc06-4a5c-8408-2b0448205880.png)

**Comment by Hellobloc** [comment]
No vulnerability bounty will endorse this kind of dos attack that requires a lot of traffic to carry out, strictly speaking this thing is bound to exist. Suggest you go to a university to learn about information security

**Comment by Hellobloc** [comment]
If all the hackers in the world were people like you, the world would be a very safe place!
