### ISSUE TITLE
is there a reward for digging out blocks？

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1218]
In the avalanche chain, is there a reward for digging out blocks, and what is the reward mechanism

**Comment by abi87** [comment]
The reward is granted based on the uptime and responsiveness of nodes, rather than on block production.
You can find more information [in our docs](https://docs.avax.network/). For instance:

1. [conditions for validators to receive rewards](https://docs.avax.network/nodes/validate/staking#how-is-it-determined-whether-a-validator-receives-a-staking-reward)
2. [conditions for delegators to receive rewards](https://docs.avax.network/nodes/validate/staking#delegator-rewards)
3. [the reward formula](https://docs.avax.network/subnets/reference-elastic-subnets-parameters#reward-formula)

**Comment by abebeos** [comment]
Looks closable

**Comment by abi87** [comment]
Closing it down
