### ISSUE TITLE
Potential invalid memory access in syncWorkHeap

### ISSUE THREAD

**Issue by dnkolegov** [ava-labs/avalanchego#1520]
`GetWork` [function](https://github.com/ava-labs/avalanchego/blob/e2b4d9a9cdcaa297b66adab783dad35bfa10cbe1/x/sync/syncworkheap.go#L62) can return `nil`.

The callers of `GetWork` do not check whether the returned result is not nil:
- in [`sync`](https://github.com/ava-labs/avalanchego/blob/2806af77d377851b9e0d4809dedb13fd17821fd0/x/sync/syncmanager.go#L197) when calling [`doWork`](https://github.com/ava-labs/avalanchego/blob/2806af77d377851b9e0d4809dedb13fd17821fd0/x/sync/syncmanager.go#L239)
- in [`UpdateSyncTarget`](https://github.com/ava-labs/avalanchego/blob/2806af77d377851b9e0d4809dedb13fd17821fd0/x/sync/syncmanager.go#L550)

**Comment by danlaine** [comment]
There are two reasons `GetWork` might return nil:
1. `Close()` has been called on `StateSyncManager`
2. There is no work in the `syncWorkHeap`

and there are two places we call `GetWork`:
1. `sync`
2. `UpdateSyncTarget`

In `sync`, suppose we are at line

```go
workItem := m.unprocessedWork.GetWork()
```

At the top of that loop we check whether `Close` has been called with:

```go
if ctx.Err() != nil { // [m] is closed.
	return // [m.workLock] released by defer.
}
```

Note that:
1. `Close` cancels the context passed into `sync`.
2. `Close` holds the `workLock`.
3. The `for` loop in `sync` holds the `workLock`.

Therefore the usage in `sync` is not an issue when the `syncWorkHeap` returns `nil` due to it being closed. It's also not an issue when the `syncWorkHeap` is empty because `unprocessedWorkCond` is only signaled when the `syncWorkHeap` is closed (covered previously) or when `syncWorkHeap` is non-empty. If it's non-empty, it won't return nil.

Similarly, the usage in  `UpdateSyncTarget` is not an issue. If we're inside this loop:

```go
	for m.processedWork.Len() > 0 {
		// Note that [m.processedWork].Close() hasn't
		// been called because we have [m.workLock]
		// and we checked that [m.closed] is false.
		currentItem := m.processedWork.GetWork()
		currentItem.priority = highPriority
		m.unprocessedWork.Insert(currentItem)
	}
```
then the `syncWorkHeap` is not empty. It's also not closed, because we hold `workLock` in `UpdateSyncTarget` and check for the `syncWorkHeap` being closed with:

```go
	select {
	case <-m.syncDoneChan:
		return ErrAlreadyClosed
	default:
	}
```

So there's actually no issue with `GetWork` returning `nil`.
