### ISSUE TITLE
Syncing is very slow, too long ETA's

### ISSUE THREAD

**Issue by samarthk-systango** [ava-labs/avalanchego#1528]
Hi Team,

I have started the avax archive node using genesis but syncing is very slow from last 5 days. Followed below document to setup AVAX node.

**Doc link** - https://docs.avax.network/nodes/build/run-avalanche-node-manually

**Node-1 ETA : INFO <C Chain> queue/jobs.go:203 executing operations {"numExecuted": 8514386, "numToExecute": 29769169, "eta": "268h40m14s"}

Node-2 ETA : INFO <C Chain> queue/jobs.go:203 executing operations {"numExecuted": 1046408, "numToExecute": 19719584, "eta": "745h4m58s"}**

**Configuration :**

- Dowloaded installer from below location :
wget -nd -m https://raw.githubusercontent.com/ava-labs/avalanche-docs/master/scripts/avalanchego-installer.sh;\
chmod 755 avalanchego-installer.sh;\

- Using below command to start the service
./avalanchego-installer.sh --archival --db-dir /data/avalanche/database

- Bootstrapping and Pruning is disabled

**Here are the hardware details for which we are using for both the nodes :**

NODE1 :
Machine: Standard D4as v5 
vCPU: 4
RAM: 16GB
Disk attached: 8 TB

NODE2 :
Machine: Standard L16as v3 
vCPU: 16
RAM: 128GB
Disk attached: 12 TB

**Below are the current log snippet of both the nodes.**

Node-1 :
![Screenshot from 2023-05-19 16-16-50](https://github.com/ava-labs/avalanchego/assets/128302698/0f6d7d34-9a1b-4edf-b082-78d3f5f6a781)

Node-2 :
![Screenshot from 2023-05-19 16-22-22](https://github.com/ava-labs/avalanchego/assets/128302698/07669b47-a0f7-442c-9e24-a12b664bd75a)

**Comment by StephenButtolph** [comment]
## Ways to speed up execution

Synching an archival node is primarily bottlenecked by DB IO - so increasing IOPs will improve performance. Additionally, the C-chain config exposes cache configurations that can be increased to reduce DB IO. Specifically:
- [`trie-clean-cache`](https://docs.avax.network/nodes/maintain/chain-config-flags#trie-clean-cache-int)
- [`snapshot-cache`](https://docs.avax.network/nodes/maintain/chain-config-flags#snapshot-cache-int)

## Open to suggestions for how to improve

If there are any concrete suggestions or profiles showing unexpected hot-spots that are being observed, I'd love to hear / see them so we could improve this process.

## Disclamer about archival nodes

Syncing an archival node is going to be very slow - as it needs to fully re-execute all the chains (the primary bottleneck being the C-chain, as we can see in the above pictures). Because the prior block state is required to process the next block, this process isn't easy to parallelize.

Technically, someone could develop an archival node syncing approach that
1. Splits the chain into subsections (based on how performant the node is).
2. State syncs the beginning of each subsection off of existing archival nodes.
3. Executes the subsections in parallel.

However, I would argue that the current design of archival nodes (across the blockchain industry as a whole) is fundamentally unsustainable. AKA - I don't think storing the entire history of an ever growing ledger on a single computer/disk is scalable. Especially when the primary bottleneck of execution is disk latency.

IMO an "archival node" can only possibly be implemented as itself a distributed (scalable) database.

I'm not trying to suggest that the implementation can't be improved, [Erigon](https://github.com/ledgerwatch/erigon) is designed around trying to make archival nodes as efficient as possible for Ethereum... But AvalancheGo makes no such attempt.
