### ISSUE TITLE
Any way to edit the weight of validators for a subnet?

### ISSUE THREAD

**Issue by friskyfoxdk** [ava-labs/avalanchego#1627]
We are wanting to temporarily change the weight of one of our validators so we can experiment with some new hardware. My question is, would this have any negative side effects we should be aware of? For example, changing one of our validators to weight 1 for a little while.

Seems like we would have 8 nodes running with a combined 7001 weight, so if the node with 1 weight goes down, and another one of our 1000 weight goes down, we would have 6000/7001 nodes up and still be above the 75% consensus threshold. Am I thinking of this correctly?

Also, does the weight value govern how often a node is selected to produce a block?

Also, correct me if i’m wrong, but it seems like we’d have to first remove the validator and then add it again with the new weight, right?

```
subnet-cli remove subnet-validator \
--ledger \
--public-uri https://api.avax.network/ \
--node-ids="NodeID-BaTDuWRvZkEy8gg4FRYmNYXASWL4QKzFD" \
--subnet-id="Vn3aX6hNRstj5VHHm63TCgPNaeGnRSqCYXQqemSqDd2TQH4qJ"
```

```
subnet-cli add subnet-validator \
--node-ids="NodeID-BaTDuWRvZkEy8gg4FRYmNYXASWL4QKzFD" \
--subnet-id="Vn3aX6hNRstj5VHHm63TCgPNaeGnRSqCYXQqemSqDd2TQH4qJ" \
--ledger \
--public-uri https://api.avax.network/ \
--validate-weight=1
```

**Comment by StephenButtolph** [comment]
> Seems like we would have 8 nodes running with a combined 7001 weight, so if the node with 1 weight goes down, and another one of our 1000 weight goes down, we would have 6000/7001 nodes up and still be above the 75% consensus threshold. Am I thinking of this correctly?

This is correct. `6000/7001 ~= 85%`. With the default `alpha / k = 15/20 = 75%` the network would be able to tolerate `1` of the nodes with `1000` weight going down. If `2` of the nodes with `1000` weight goes down, the online stake would fall to `~70%` which would not be able to finalize blocks. In this configuration, the node with weight `1` will have essentially no impact on the network health. This means that it could go offline with no impact.

> Also, does the weight value govern how often a node is selected to produce a block?

Yes. The block proposer list is stake weighted. Although once the list is exhausted any node (regardless of validator status or weight) could propose a block.

> Also, correct me if i’m wrong, but it seems like we’d have to first remove the validator and then add it again with the new weight, right?

This is correct, there is no way to update the weight of a validator during it's staking period (other than removing it from the validator set and re-introducing it with different parameters).

---

Expanding on the `alpha / k` bounds, consensus needs to see `beta` consecutive polls with `alpha` out of `k` votes affirmatively voting for a decision to confirm the decision. Using this calculator: https://stattrek.com/online-calculator/hypergeometric we can plug in the situation:

```
Population size                   = 7001
Number of successes in population = 6000
Sample size                       = 20
Number of successes in sample     = 15
```

Running this we should see:

<img width="343" alt="Screenshot 2023-06-15 at 5 31 06 PM" src="https://github.com/ava-labs/avalanchego/assets/22109487/44dbd298-1142-42bb-82f9-4a2f0253b1b2">

Since `BetaVirtuous = 15` by default, the probability of a given run of `15` polls will have `0.94494^15` chance of terminating. Which comes out to around `0.43`. Which means that the network will be able to easily confirm the blocks in short order.

However, if another node with `1000` weight were to go down:

```
Population size                   = 7001
Number of successes in population = 5000
Sample size                       = 20
Number of successes in sample     = 15
```

Running this we should see:

<img width="343" alt="Screenshot 2023-06-15 at 5 35 21 PM" src="https://github.com/ava-labs/avalanchego/assets/22109487/1110b637-0cbd-422c-8d5c-674930401144">

The probability of a given run of `15` polls would now have `0.47176^15` chance of terminating. Which comes out to around `.000013`. Which means that the network would not be able to timely confirm blocks.

---

Let me know if this doesn't make sense or if you have any other questions.

**Comment by friskyfoxdk** [comment]
Thanks @StephenButtolph , this was very helpful!
