### ISSUE TITLE
Please give me some examples about

### ISSUE THREAD

**Issue by godlovericea** [ava-labs/avalanchego#3507]
I want to transfer AVAX from one address to another on X-Chain
but the lib and docs are too difficulty to me
please give me some examples
thanks

**Comment by StephenButtolph** [comment]
Are you looking for a front-end wallet?

Or are you specifically looking for an example golang program to transfer X-chain funds?

**Comment by godlovericea** [comment]
i am  looking for an example golang program to transfer X-chain funds

**Comment by StephenButtolph** [comment]
[here](https://github.com/ava-labs/avalanchego/blob/739544eaf2bc33a683d15ab7b80f90a73e574b3d/wallet/subnet/primary/examples/create-asset/main.go) is an example for creating an X-chain asset. Using [IssueBaseTx](https://github.com/ava-labs/avalanchego/blob/739544eaf2bc33a683d15ab7b80f90a73e574b3d/wallet/chain/x/wallet.go#L27-L34) rather than `IssueCreateAssetTx` would perform a simple asset transfer.
