### ISSUE TITLE
P-Chain: Discrepancy of a transaction's output

### ISSUE THREAD

**Issue by infsaulo** [ava-labs/avalanchego#3603]
**Describe the bug**
Querying a Tx on P-Chain via the RPC endpoint is missing one output.

**To Reproduce**
1. Query the transaction RPC endpoint of P-Chain: 
`curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getTx",
    "params": {
        "txID": "2EFJ2PYS9SDdkYzJJPvoa7AxMF4ayuptCxap6FWZFj8ydHXQYL",
        "encoding": "json"
    },
    "id": 1
}' -H 'content-type:application/json;' https://api.avax.network/ext/bc/P | jq`

2. Compare with https://subnets.avax.network/p-chain/tx/2EFJ2PYS9SDdkYzJJPvoa7AxMF4ayuptCxap6FWZFj8ydHXQYL

**Expected behavior**

When querying the RPC for this transaction, there should be two outputs. However, currently, the transaction queried via RPC has just one output.

**Comment by infsaulo** [comment]
Additional Detail:

When querying the transaction `iD9VwJREWCieLpqpQ7gEXWCHQPdu9vSTa2pEsCcgBvGJxakny` with:
```curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getTx",
    "params": {
        "txID": "iD9VwJREWCieLpqpQ7gEXWCHQPdu9vSTa2pEsCcgBvGJxakny",
        "encoding": "json"
    },
    "id": 1
}' -H 'content-type:application/json;' https://api.avax.network/ext/bc/P | jq
``` 

The input in this transaction refers to the output with index `1` from tx `2EFJ2PYS9SDdkYzJJPvoa7AxMF4ayuptCxap6FWZFj8ydHXQYL`. 

However, as explained above, querying `2EFJ2PYS9SDdkYzJJPvoa7AxMF4ayuptCxap6FWZFj8ydHXQYL` returns just one output, thus index `0`.

**Comment by meaghanfitzgerald** [comment]
It looks like this is releasing the previously locked funds and therefore creating a new UTXO, which is not included in the tx itself: https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/txs/executor/standard_tx_executor.go#L1031

The UTXOs found in the transaction are included in the `baseTx`, but on the P-Chain if the "operation" the tx is performing creates another UTXO, then it will be displayed by the explorer, but not show up in the JSON of the tx (because it's not actually part of the tx data itself)
