### ISSUE TITLE
"to" parameter in "avm.exportAVAX" API seems like no funnctioning

### ISSUE THREAD

**Issue by aktorun** [ava-labs/avalanchego#384]
**Describe the bug**
There are 3 P-Chain addresses belongs to the same user. PC1, PC2 and PC3.
User tries to send some funds to the PC1 by issuing avm.exportAVAX.
In parameter section of the API command, user mentions the PC1 address and amount as 2M AVAX.
And without issuing an import command, user sends some funds to the PC2. Again in parameter section of the API user specifies PC2 address and 2M AVAX.
And user runs platform.importAVAX command with PC3 address in parameter. Strangely, command works without problem and all funds (4M -fees) move to PC3.

**To Reproduce**
avm.exportAVAX => PC1, 2M AVAX
avm.exportAVAX => PC2, 2M AVAX
platform.importAVAX => PC3
platform.importAVAX => PC1
platform.importAVAX => PC2

**Expected behavior**
I would expect to see, first command would fail since I stated only PC1 and PC2 with exportAVAX commands. And 2M on each PC1 and PC2 (- fees) at the end. But reality first command moved all funds (4M-fees) to PC3 :)

**Screenshots**
[GitHub - exportAVAX APIs TO parameter doesnt function.txt](https://github.com/ava-labs/gecko/files/5198080/GitHub.-.exportAVAX.APIs.TO.parameter.doesnt.function.txt)

**Operating System**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by StephenButtolph** [comment]
To clarify what's happening here:

By specifying PC1 and PC2 in their `ExportTx`s, a user controlling PC1 will be able to import the funds. Similarly for PC2. Because the user that is issuing the `ImportTx` has authorization of both PC1 and PC2, it's able to import both those funds, and send them to PC3 as specified in the `ImportTx`.

avm.exportAVAX(Destination=PC1, Amount=2M AVAX) => Any user that controls PC1 can import these funds
avm.exportAVAX(Destination=PC2, Amount=2M AVAX) => Any user that controls PC2 can import these funds
platform.importAVAX(Destination=PC3) => If this is called with a user that controls PC1 and PC2, then both those addresses will be used to import AVAX to PC3.

I'm going to change this from a bug to a documentation request, as we should probably better explain the details of `importAVAX` calls.

**Comment by aktorun** [comment]
Thanks for the clarification.
