### ISSUE TITLE
Port Forwarding (9651) crashes AVAX node.

### ISSUE THREAD

**Issue by DiCrypt1d** [ava-labs/avalanchego#442]
On fresh installed ubuntu 20 (ubuntu internal firewall is disabled) AVAX node 1.0 works totally fine until port 9651 is forwarded. If I forward this port on my external firewall to the node it can't start and gives this error.

INFO [09-23|16:06:09] api/server.go#82: HTTP API server listening on "127.0.0.1:9650"
FATAL[09-23|16:06:20] node/node.go#185: Failed to connect to bootstrap nodes. Node shutting down...

Removing port forwarding solves the problem and node starts normally. This bug is new to the 1.0 version. Haven't seen it at 0.8.

**Comment by quasarati** [comment]
I see the same thing. It started from 1.0. what is weird that for me I started avalanchego with a bash script in the background.
The scripts runs the binary in a loop in case it crashes.

When I start it in the background:
$ ./avalanchego &                                                                                                           
$      _____               .__                       .__                                                                    
    /  _  \___  _______  |  | _____    ____   ____ |  |__   ____    ,_ o                                                    
   /  /_\  \  \/ /\__  \ |  | \__  \  /    \_/ ___\|  |  \_/ __ \   / //\,                                                  
  /    |    \   /  / __ \|  |__/ __ \|   |  \  \___|   Y  \  ___/    \>> |                                                  
  \____|__  /\_/  (____  /____(____  /___|  /\___  >___|  /\___  >    \\                                                    
          \/           \/          \/     \/     \/     \/     \/                                                           
WARN [09-27|10:34:37] main/main.go#96: NAT traversal has failed. The node will be able to connect to less nodes.            
INFO [09-27|10:34:37] node/node.go#736: Node version is: avalanche/1.0.0                                                    
INFO [09-27|10:34:39] node/node.go#379: Set node's ID to DhNYzUwYHPF24Wfz9MmmVyqLBUF6tkEpb                                  
INFO [09-27|10:34:39] node/node.go#441: Initializing API server                                                             
INFO [09-27|10:34:39] node/node.go#567: initializing keystore                                                               
INFO [09-27|10:34:39] node/node.go#578: initializing keystore API                                                           
INFO [09-27|10:34:39] api/server.go#152: adding route /ext/keystore                                                         
INFO [09-27|10:34:39] node/node.go#594: initializing metrics API                                                            
INFO [09-27|10:34:39] api/server.go#152: adding route /ext/metrics                                                          
INFO [09-27|10:34:39] node/node.go#559: initializing SharedMemory                                                           
INFO [09-27|10:34:41] api/server.go#152: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT             
INFO [09-27|10:34:41] api/server.go#152: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq             
 
(Blocks here, after a while I press enter,then this happens)                                                                                                                           
[1] + Stopped (tty output)       ./avalanchego                                                                              
$                                                                                                                           
$ fg                                                                                                                        
./avalanchego                                                                                                               
FATAL[09-27|10:35:19] node/node.go#185: Failed to connect to bootstrap nodes. Node shutting down...                         
INFO [09-27|10:35:20] node/node.go#610: skipping admin API initialization because it has been disabled                      
INFO [09-27|10:35:20] node/node.go#626: initializing info API                                                               
INFO [09-27|10:35:20] api/server.go#152: adding route /ext/info                                                             
INFO [09-27|10:35:20] node/node.go#650: initializing Health API                                                             
INFO [09-27|10:35:20] api/server.go#152: adding route /ext/health                                                           
INFO [09-27|10:35:20] node/node.go#688: skipping ipc API initializaion because it has been disabled                         
INFO [09-27|10:35:20] node/node.go#701: initializing aliases                                                                
INFO [09-27|10:35:20] node/node.go#425: initializing chains                                                                 
INFO [09-27|10:35:20] chains/manager.go#188: creating chain:                                                                
    ID: 11111111111111111111111111111111LpoYY                                                                               
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT                                                                  
INFO [09-27|10:35:21] <P Chain> vms/platformvm/vm.go#399: Initializing last accepted block as 27spnTEF6bfF4EuDTGYanEtGGwmhPr
9vQp4sTDDJGoEgQD52a9                                                                                                        
INFO [09-27|10:35:21] <P Chain> snow/engine/snowman/transitive.go#58: initializing consensus engine                         
INFO [09-27|10:35:21] api/server.go#136: adding route /ext/bc/11111111111111111111111111111111LpoYY                         
INFO [09-27|10:35:21] node/node.go#810: shutting down the node                                                              
INFO [09-27|10:35:21] <P Chain> snow/engine/snowman/transitive.go#133: shutting down consensus engine                       
INFO [09-27|10:35:21] api/server.go#82: HTTP API server listening on "127.0.0.1:9650"                                       
INFO [09-27|10:35:22] <P Chain> snow/networking/router/handler.go#487: finished shutting down chain                         
INFO [09-27|10:35:22] node/node.go#816: node shut down successfully                                                         
INFO [09-27|10:35:22] nat/nat.go#140: Unmapped all ports   


It wil run normally when I run it in the foreground. I can move it to the background by using ctrl-z + the bg command after it started

**Comment by quasarati** [comment]
It have port forwarding setup but get the NAT traveral warning anyway. Not sure why. Doesn't matter if I add in the public IP address with --public-ip=

**Comment by dbrisinda** [comment]
On a related note, I'm getting errors after the node runs for a day or two, that causes the node to no longer be accessible by the network. This is the the error that is shown:

ERROR[09-27|12:25:09] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Ports 9650-9652 are forwarded (just in case). But same problem was happening even before port forwarding on router. Note using --public-ip= as I don't have a static IP.

**Comment by DiCrypt1d** [comment]
New addition.
If I start the node with **disabled** port forwarding for 9651 port and immediately forward this port **after** node passes the boot line
`"HTTP API server listening on "127.0.0.1:9650"`
than the node does not crashes and connects to more nodes.

**Comment by DiCrypt1d** [comment]
It seems to be fixed in 1.0.2. Thanks.

**Comment by hakangurrr** [comment]
**I see the same thing.** 

I'm getting errors after the node runs for a day or two.

I started node with docker.
`
docker run -v ~/ava/backup/.avalanchego/:/root/.avalanchego/ -d -p 9651:9651 -p 9650:9650 [Image_Id] /avalanchego/build/avalanchego --public-ip=46.2.163.117`

INFO [05-06|07:28:31] main/process/process.go#156: this node's IP is set to: 46.2.163.117:9651
INFO [05-06|07:28:31] node/node.go#881: Node version is: avalanche/1.4.1
INFO [05-06|07:28:31] node/node.go#419: Set node's ID to NodeID-Gutrj2oWq4no19QnzGNKuNrfeBQ6ao4kg
INFO [05-06|07:28:31] node/node.go#504: initializing API server
INFO [05-06|07:28:31] api/server/server.go#70: API created with allowed origins: [*]
INFO [05-06|07:28:31] node/node.go#687: initializing keystore
INFO [05-06|07:28:31] node/node.go#698: initializing keystore API
INFO [05-06|07:28:31] api/server/server.go#172: adding route /ext/keystore
INFO [05-06|07:28:31] node/node.go#721: initializing metrics API
INFO [05-06|07:28:31] api/server/server.go#172: adding route /ext/metrics
INFO [05-06|07:28:31] node/node.go#679: initializing SharedMemory
INFO [05-06|07:28:31] node/node.go#779: initializing Health API
INFO [05-06|07:28:31] api/server/server.go#172: adding route /ext/health
INFO [05-06|07:28:32] api/server/server.go#172: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [05-06|07:28:32] api/server/server.go#172: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [05-06|07:28:33] node/node.go#737: skipping admin API initialization because it has been disabled
INFO [05-06|07:28:33] node/node.go#753: initializing info API
INFO [05-06|07:28:33] api/server/server.go#172: adding route /ext/info
INFO [05-06|07:28:33] node/node.go#829: skipping ipc API initialization because it has been disabled
INFO [05-06|07:28:33] node/node.go#842: initializing aliases
INFO [05-06|07:28:33] node/node.go#490: initializing chains
INFO [05-06|07:28:33] chains/manager.go#211: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [05-06|07:28:41] <P Chain> vms/platformvm/vm.go#334: initializing last accepted block as 2Tza5jMJCDK5hke3zkafrRnuHNpmE6H8Sn7LR5ygyQEkQ7K52d
INFO [05-06|07:28:41] <P Chain> snow/engine/snowman/transitive.go#64: initializing consensus engine
INFO [05-06|07:28:41] <P Chain> snow/engine/common/bootstrapper.go#71: Starting bootstrap...
INFO [05-06|07:28:41] api/server/server.go#156: adding route /ext/bc/11111111111111111111111111111111LpoYY
INFO [05-06|07:28:41] api/server/server.go#88: HTTP API server listening on "127.0.0.1:9650"
INFO [05-06|07:29:11] health/service.go#125: "network" became healthy with: {"message":{"connectedPeers":4,"sendFailRate":0.00012559978312559156,"sendQueuePortionFull":0,"timeSinceLastMsgReceived":"260.130052ms","timeSinceLastMsgSent":"260.130052ms"},"timestamp":"2021-05-06T07:29:11.26004983Z","duration":79555,"contiguousFailures":0,"timeOfFirstFailure":null}
WARN [05-06|07:29:31] node/node.go#209: Failed to connect to bootstrap nodes. Node shutting down...
INFO [05-06|07:29:31] node/node.go#960: shutting down node
INFO [05-06|07:29:31] ipcs/chainipc.go#101: shutting down chain IPCs
INFO [05-06|07:29:31] chains/manager.go#693: shutting down chain manager
INFO [05-06|07:29:31] snow/networking/router/chain_router.go#169: shutting down chain router
INFO [05-06|07:29:31] <P Chain> snow/engine/snowman/transitive.go#150: shutting down consensus engine
INFO [05-06|07:29:35] network/network.go#916: shutting down network
INFO [05-06|07:29:36] node/node.go#981: finished node shutdown
INFO [05-06|07:29:36] nat/nat.go#152: Unmapped all ports

**Starting again...**

INFO [05-06|07:29:54] main/process/process.go#156: this node's IP is set to: 46.2.163.117:9651
INFO [05-06|07:29:54] node/node.go#881: Node version is: avalanche/1.4.1
INFO [05-06|07:29:54] node/node.go#419: Set node's ID to NodeID-Gutrj2oWq4no19QnzGNKuNrfeBQ6ao4kg
INFO [05-06|07:29:54] node/node.go#504: initializing API server
INFO [05-06|07:29:54] api/server/server.go#70: API created with allowed origins: [*]
INFO [05-06|07:29:54] node/node.go#687: initializing keystore
INFO [05-06|07:29:54] node/node.go#698: initializing keystore API
INFO [05-06|07:29:54] api/server/server.go#172: adding route /ext/keystore
INFO [05-06|07:29:54] node/node.go#721: initializing metrics API
INFO [05-06|07:29:54] api/server/server.go#172: adding route /ext/metrics
INFO [05-06|07:29:54] node/node.go#679: initializing SharedMemory
INFO [05-06|07:29:54] node/node.go#779: initializing Health API
INFO [05-06|07:29:54] api/server/server.go#172: adding route /ext/health
INFO [05-06|07:29:55] api/server/server.go#172: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [05-06|07:29:55] api/server/server.go#172: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [05-06|07:29:57] node/node.go#737: skipping admin API initialization because it has been disabled
INFO [05-06|07:29:57] node/node.go#753: initializing info API
INFO [05-06|07:29:57] api/server/server.go#172: adding route /ext/info
INFO [05-06|07:29:57] node/node.go#829: skipping ipc API initialization because it has been disabled
INFO [05-06|07:29:57] node/node.go#842: initializing aliases
INFO [05-06|07:29:57] node/node.go#490: initializing chains
INFO [05-06|07:29:57] chains/manager.go#211: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [05-06|07:30:05] <P Chain> vms/platformvm/vm.go#334: initializing last accepted block as 2Tza5jMJCDK5hke3zkafrRnuHNpmE6H8Sn7LR5ygyQEkQ7K52d
INFO [05-06|07:30:05] <P Chain> snow/engine/snowman/transitive.go#64: initializing consensus engine
INFO [05-06|07:30:05] <P Chain> snow/engine/common/bootstrapper.go#71: Starting bootstrap...
INFO [05-06|07:30:05] api/server/server.go#156: adding route /ext/bc/11111111111111111111111111111111LpoYY
INFO [05-06|07:30:05] api/server/server.go#88: HTTP API server listening on "127.0.0.1:9650"
INFO [05-06|07:30:34] health/service.go#125: "network" became healthy with: {"message":{"connectedPeers":2,"sendFailRate":0.00035660499753026683,"sendQueuePortionFull":0,"timeSinceLastMsgReceived":"580.213572ms","timeSinceLastMsgSent":"580.213572ms"},"timestamp":"2021-05-06T07:30:34.580088962Z","duration":115944,"contiguousFailures":0,"timeOfFirstFailure":null}
WARN [05-06|07:30:54] node/node.go#209: Failed to connect to bootstrap nodes. Node shutting down...
INFO [05-06|07:30:54] node/node.go#960: shutting down node
INFO [05-06|07:30:54] ipcs/chainipc.go#101: shutting down chain IPCs
INFO [05-06|07:30:54] chains/manager.go#693: shutting down chain manager
INFO [05-06|07:30:54] snow/networking/router/chain_router.go#169: shutting down chain router
INFO [05-06|07:30:54] <P Chain> snow/engine/snowman/transitive.go#150: shutting down consensus engine
INFO [05-06|07:30:58] network/network.go#916: shutting down network
INFO [05-06|07:30:58] node/node.go#981: finished node shutdown
INFO [05-06|07:30:58] nat/nat.go#152: Unmapped all ports

**Comment by otherview** [comment]
Hi @hakangurrr , it seems the error you're having is not related to port forwarding.

```
WARN [05-06|07:29:31] node/node.go#209: Failed to connect to bootstrap nodes. Node shutting down...
```

That's something that was addressed on the 1.4.1 - please ensure you're running the latest image `docker pull avaplatform/avalanchego:v1.4.1`

Thanks

**Comment by hakangurrr** [comment]
Hi @otherview 

I had a same issue 1.3.1 version. So I updated node ( git pull origin master, delete existing container and image, create new image and container, run docker with volume) and run it again. I'm getting same error latest version.

**Comment by otherview** [comment]
Could be related to the network. Try using the flag `--bootstrap-retry-max-attempts=1000` .

If you still have problems, can you please use the official Discord channel or create a new issue.
