### ISSUE TITLE
Node unable to bootstrap with `--staking-enabled=false`

### ISSUE THREAD

**Issue by sezu** [ava-labs/avalanchego#842]
**Describe the bug**
Node unable to bootstrap

**To Reproduce**
Run node with staking disabled

```
--staking-enabled=false
```

**Expected behavior**
I expect the node to bootstrap

**Operating System**
Ubuntu 18.04

**Additional context**
```
"DEBUG[05-12|22:38:10] <C Chain> /src/snow/engine/snowman/transitive.go#650: block failed verification due to rpc error: code = Unknown desc = invalid block due to failed semanatic verify: failed to fetch import UTXOs from 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM with rpc error: code = Unknown desc = not found at height 1713542, dropping block" 
```

**Comment by aaronbuchwald** [comment]
You should not be running with staking disabled on any production networks. The `staking-enabled` flag means that your node will count every validator equally instead of weighting them by stake amount, such that your node will be vulnerable to sybil attacks.

You may need to wipe your database and start your node from scratch because running with staking disabled could have caused corruption on your node.

**Comment by sezu** [comment]
That's good to know. Thanks for the info.
