### ISSUE TITLE
Cannot remove AvalancheGo

### ISSUE THREAD

**Issue by RicTicMiami** [ava-labs/avalanchego#957]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Operating System**
Which OS you used to reveal the bug.

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by RicTicMiami** [comment]
On a MacBook with Monterey:
I ran go get -v -d github.com/ava-labs/avalanchego/...
First issue - the src was not in cd $GOPATH/src/github.com/ava-labs/avalanchego, it was in :
$GOPATH/pkg/mod/github.com/..
cd ava-labs/avalanchego@v1.7.1
Attempting to run ./scripts/build.sh - permission denied, since it was read-only
Chmod +x on build.sh 
Execute build yields "fatal: not a git repository (or any of the parent directories): .git"
OK. Resolved that the clone was not successful - attempting to remove:
All files cannot be removed because of errors like this
pkg/mod/github.com/!microsoft/go-winio@v0.4.14/pkg/etw/ptr64_32.go: Permission denied
Even though I own them!

**Comment by danlaine** [comment]
@RicTicMiami 

As of Go 1.16, module-aware mode is enabled by default, which is why it downloaded AvalancheGo to `$GOPATH/pkg/mod`. See [here](https://go.dev/doc/go1.16#modules).

To download the AvalancheGo source code, do `git clone https://github.com/ava-labs/avalanchego.git`.

I suggest that you don't delete anything inside `$GOPATH/pkg/mod` unless you have a good reason to.
