### ISSUE TITLE
Seeing already confirmed transactions under "pendingTransactions" 

### ISSUE THREAD

**Issue by chiragpandya7** [ava-labs/avalanchego#958]
When subscribing to "pendingTransactions" via web3 eth.subscribe, I am seeing transactions that are already confirmed.

I've tried enabling "allow-unfinalized-queries" flag to true for C chain config, as suggested on Avalanche discord, but that didn't work. 

I've installed Avalanche node from pre-built binary. 

Node version : 1.7.1.

My C chain config are as follows : 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/31741786/143881204-db1285c7-58ea-4f19-9ffa-320f576bd015.png">

Thanks in advance.

**Comment by grGred** [comment]
I have the same issue there. Is there any way to see mempool?

**Code**

Let's set a Pending Transaction Filter:
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newPendingTransactionFilter","params":[],"id":73}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/C/rpc`

Returns:
`{"jsonrpc":"2.0","id":73,"result":"0xfab5cdb61bf97fe1ec1e278aa9b1a7bd"}`

After that get filter changes:
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xfab5cdb61bf97fe1ec1e278aa9b1a7bd"],"id":73}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/C/rpc`

Returns:
`{"jsonrpc":"2.0","id":73,"result":["0x155202de877c44d97e343622843766701285fa275280a6781b18a4dfc765d34b","0x7a2e6cb0ba5ab522d2626776356ff894ac5f5cb17c47d6ee43cec8d5d63fa8bd","0x0fae6416719355732081e25cc0bf994319d294469849387348ad00b8a41eacd2", ...`

**Expected behavior**

getTransaction request will return:
 `{'blockHash': 'null', 'blockNumber': 'null', ...`

**Actual behavior**
getTransaction request returns list of last transactions:
`{'blockHash': '0xa6cfdfc1f569427eb8f835f36f89fff59b8b65c5962ad591ddfd65c15c565c3e', 'blockNumber': '0x86db54', 'from'...`

**Comment by grGred** [comment]
You need to be a validator to see mempool, the problem is solved.
https://github.com/ava-labs/avalanchego/issues/979
