### ISSUE TITLE
Cold bootstrap seems unnecessarily slow

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#995]
**Describe the improvement**
Cold bootstrap takes a long time (hours) with Avalanche which makes recovery scenarios quite risky for validator nodes due to high uptime requirements. 

Avalanchego shouldn't need to retrieve all blocks for a chain before executing state transitions. Executing state transitions as soon as the first set of blocks are received would make cold bootstrap times almost twice as fast as I understand from my own observation (on a low-end hardware).

Similarly, a new chain could be immediately fetched while state transitions are executed for the previous chain. Currently, it looks like this:

```
thread 1: [.....fetch P......][.......execute P.....][..........fetch X........][.......execute X]
```

This should be possible instead:

```
thread 1: [.....fetch P......][..........fetch X........]
thread 2:  [.......execute P.....]
thread 3:                      [.......execute X]
```

Obviously, this would increase the CPU-load of an Avalanche node during bootstrap, but I believe cut-down bootstrap times can easily make up for it.

**Operating System**
Linux 3.10.108 x86_64 Braswell

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by StephenButtolph** [comment]
The P-chain must have actually finished bootstrapping before all other chains start fetching. This is because we use the P-chain's validator sets to initialize bootstrapping of the other chains. This is because other chains may not be validated by the nodes bootstrapping the P-chain (We could make a special case for the primary subnet here, but I'm not a super big fan of that tbh).

As for executing at the same time as fetching, currently blocks are actually fetched towards genesis, not from genesis to tip. There are some optimizations in the pipeline to improve this flow though :)

**Comment by abi87** [comment]
Hello @ssg,
We have just added some documentation explaining the bootstrap process [here](https://docs.avax.network/nodes/maintain/node-bootstrap). It contains and expand information already provided by @StephenButtolph.
I am going ahead and closing down this issue. You are welcome to open another one, here or in [our docs repo](https://github.com/ava-labs/avalanche-docs/issues) should there be more questions.
